version: '3'
networks:
  temporal-network:
    external: true

services:
  webhook-server:
    build:
      context: .
    container_name: webhook-server
    env_file:
      - .env
    command: ['npm', 'run', 'server']
    networks:
      - temporal-network
    restart: unless-stopped

  temporal-worker:
    build:
      context: .
    container_name: temporal-worker
    command: ['npm', 'run', 'start']
    networks:
      - temporal-network
    restart: unless-stopped

  mail-worker:
    build:
      context: .
    container_name: mail-worker
    command: ['npm', 'run', 'mail-worker']
    networks:
      - temporal-network
    restart: unless-stopped

